#!/bin/bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Remove pre-existing busybox executables, and replace with busybox.
#======================================================================================================================


cd /usr/bin

X=(`busybox --list`)
REMOVE=("diff" "du" "find" "sort" "expr" "nl" "tac" "stat" "factor" "xargs" "tail" "od" "ipcs")

for A in ${X[@]} ; do

    if printf '%s\0' "${REMOVE[@]}" | grep -Fxqz -- '${A}'; then
        [[ -f "${A}" ]] && rm -f ${A}
    fi

done

busybox --install


#======================================================================================================================
# Set timezone.
#======================================================================================================================

bf-tz "Europe/London"
