#!/bin/sh

set -euo pipefail


#======================================================================================================================
# Run custom initialisation files.
#======================================================================================================================

INIT=/etc/bf/init.d
for FILE in `ls ${INIT} | sort` ; do
    bf-echo "${FILE}: Running..."
    chmod +x ${INIT}/${FILE} && ${INIT}/${FILE}
    bf-echo "${FILE}: done."
done
