name: auto-pr

on:
  create

jobs:
  create-pr:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Branch ${{ github.ref_name }}
        uses: actions/checkout@v4
      -
        name: Create Pull Request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "${{ github.ref_name }}" --body "Merging branch to create ${{ github.ref_name }}."
