name: dev

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  workflow_dispatch:

env:
  TEST_TAG: bfren/debian:test

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        debian: [ "11", "12" ]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read Debian name
        uses: bfren/read-file@v2
        with:
          file: ./${{ matrix.debian }}/DEBIAN_NAME
        id: debian_name
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and export
        id: docker_export
        uses: docker/build-push-action@v6
        with:
          file: ./${{ matrix.debian }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Run tests
        id: docker_test
        run: |
          docker run --entrypoint /test ${{ env.TEST_TAG }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.debian }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: ${{ startsWith(github.ref, 'refs/heads/') }}
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            bfren/debian:debian${{ matrix.debian }}-dev
            bfren/debian:debian${{ matrix.debian }}-${{ steps.version_major.outputs.contents }}-dev
            bfren/debian:debian${{ matrix.debian }}-${{ steps.version_minor.outputs.contents }}-dev
            bfren/debian:debian${{ matrix.debian }}-${{ steps.version.outputs.contents }}-dev
            bfren/debian:${{ steps.debian_name.outputs.contents }}-dev
            bfren/debian:${{ steps.debian_name.outputs.contents }}-${{ steps.version_major.outputs.contents }}-dev
            bfren/debian:${{ steps.debian_name.outputs.contents }}-${{ steps.version_minor.outputs.contents }}-dev
            bfren/debian:${{ steps.debian_name.outputs.contents }}-${{ steps.version.outputs.contents }}-dev
            ghcr.io/bfren/debian:debian${{ matrix.debian }}-dev
            ghcr.io/bfren/debian:debian${{ matrix.debian }}-${{ steps.version_major.outputs.contents }}-dev
            ghcr.io/bfren/debian:debian${{ matrix.debian }}-${{ steps.version_minor.outputs.contents }}-dev
            ghcr.io/bfren/debian:debian${{ matrix.debian }}-${{ steps.version.outputs.contents }}-dev
            ghcr.io/bfren/debian:${{ steps.debian_name.outputs.contents }}-dev
            ghcr.io/bfren/debian:${{ steps.debian_name.outputs.contents }}-${{ steps.version_major.outputs.contents }}-dev
            ghcr.io/bfren/debian:${{ steps.debian_name.outputs.contents }}-${{ steps.version_minor.outputs.contents }}-dev
            ghcr.io/bfren/debian:${{ steps.debian_name.outputs.contents }}-${{ steps.version.outputs.contents }}-dev
      -
        name: Build and push default tags
        id: docker_build_default
        if: matrix.debian == '12'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.debian }}/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: ${{ startsWith(github.ref, 'refs/heads/') }}
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            bfren/debian:dev
            bfren/debian:${{ steps.version_major.outputs.contents }}-dev
            bfren/debian:${{ steps.version_minor.outputs.contents }}-dev
            bfren/debian:${{ steps.version.outputs.contents }}-dev
            ghcr.io/bfren/debian:dev
            ghcr.io/bfren/debian:${{ steps.version_major.outputs.contents }}-dev
            ghcr.io/bfren/debian:${{ steps.version_minor.outputs.contents }}-dev
            ghcr.io/bfren/debian:${{ steps.version.outputs.contents }}-dev
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
